### ISSUE TITLE
Include more examples of including third party libraries

### ISSUE THREAD

**Issue by develpr** [infielddigital/aem-webpack-example#3]
It seems that something that comes up a lot is the best way to include third party libraries. 

For example, let's say that we wanted / needed to include jquery in a project (*gasp!*), an example of how to do that would be helpful I think.

How about something even "heavier", like Foundation or Bootstrap? 

I see [there is an example module](https://github.com/infielddigital/aem-webpack-example/tree/master/ui.apps/src/main/content/jcr_root/example) which seems like a great startign point, but a few more examples for some of the more common tasks might make this a lot easier to "get started".

**Comment by kevinweber** [comment]
Good idea.
What's your favorite approach to this? And are there concrete examples you'd like to have explained? At least jQuery makes total sense (because AEM comes with it and jQuery is so popular) but choosing another library is trickier.

I see the following ways to integrate jQuery (and most libraries):
1. Include jQuery as a dependency in your package.json, then do `import $ from 'jquery';` whenever you need it in a component. [This is my preferred approach because it promotes better modularity and people don't wonder "why can I use `$` in my module without importing it?". You can avoid conflicts with libraries that potentially could use the dollar sign as well. It's easier to refactor your code in case you decide to remove/replace jQuery.]
2. Include jQuery as a separate clientlib on the page that is loaded before you Webpack bundle. [That's might be the most common approach. It's easy and convenient.]
3. Import jQuery as one of the first scripts within your Webpack bundle so that subsequent scripts can use it without having to import it. You don't need to include a separate clientlib. [This is also an easy solution but increases your JS file significantly. So I'd avoid doing this.]

**Comment by jakegarelick** [comment]
I agree with @develpr. I think the documentation on how to get set up with aem-webpack is great, but I would love to see a more concrete example. I don't know if jQuery is a great example because AEM already includes it.

Maybe a video or something on creating a basic component with it would be nice. Like, taking a number in a text field, then using NPM's left-pad module to pad it then output it on the screen.

**Comment by id-pogni** [comment]
Kevin and I have created a wiki page explaining our recommendation for including third party libraries.

https://github.com/infielddigital/aem-webpack-example/wiki/Adding-Third-Party-Libraries

**Comment by kevinweber** [comment]
Thanks @id-pogni!
